from ctypes import set_last_error
from selenium.webdriver.common.by import By
from pages.page_base import PageBase
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.common.keys import Keys
import os, re, os.path
from time import sleep
import pyautogui as pg

class BillPaymentLocator(object):

    IMAGE_TRASH = (By.NAME, 'trash')
    BTN_OK = (By.ID, '1004')
    BTN_Cancel = (By.NAME, 'CANCEL')
    REGISTER_FORM = (By.CLASS_NAME, 'ATL:Eon00205')
    Use_different_card = (By.NAME, "Use different card")
    BTN_PROCEED = (By.NAME, "PROCEED")
    BTN_CANCEL = (By.NAME, "CANCEL")
    CLOSE_BAN = (By.ID, 'Item 10683')
    CLOSE_TOOLBAR = (By.CLASS_NAME, 'ReBarWindow32')
    MENU_BAR = (By.ID, 'MenuBar')
    DROP_TOPICS = (By.ID, 'Item 2')
    ENTER_AMOUNT= (By.NAME, 'Enter amount')
    PARENT_TOPICS = (By.CLASS_NAME, '#32768')
    CHILD_TOPICS = (By.ID, 'Item 16')
    CHILD_PAYMENT = (By.ID, 'Item 10703')
    


class Billpaymentform(PageBase):

    def bill_payment(self):

            self.click_element_advanced(BillPaymentLocator.MENU_BAR, BillPaymentLocator.DROP_TOPICS)
            sleep(2)
            self.click_element_advanced(BillPaymentLocator.PARENT_TOPICS, BillPaymentLocator.CHILD_TOPICS)
            sleep(2)
            self.click_element_advanced(BillPaymentLocator.PARENT_TOPICS, BillPaymentLocator.CHILD_PAYMENT)
            sleep(2)
            pg.press('enter')
            sleep(20)
            self.click_element_advanced(BillPaymentLocator.REGISTER_FORM, BillPaymentLocator.ENTER_AMOUNT)
            pg.enter('15')
            sleep(2)
            pg.moveTo(1046,633)
            pg.click()
            pg.click()
            pg.click()
            pg.click()
            pg.click()
            pg.moveTo(979,535)
            pg.click()
            pg.moveTo(1046,633)
            pg.click()
            pg.click()
            pg.click()
            pg.click()
            pg.click()
            sleep(2)
            self.click_element_advanced(BillPaymentLocator.REGISTER_FORM, BillPaymentLocator.Use_different_card)
            pg.click()
            pg.moveTo(1046,633)
            pg.click()
            pg.click()
            pg.click()
            pg.click()
            pg.click()
            sleep(2)
            self.click_element_advanced(BillPaymentLocator.REGISTER_FORM, BillPaymentLocator.BTN_PROCEED)
            sleep(10)
            pg.moveTo(1046,194)
            pg.click()
            pg.moveTo(654,281)
            pg.click()
            pg.write('VVV')
            pg.press('enter')
            sleep(2)
            pg.moveTo(514,315)
            pg.click()
            pg.write('4929420077965432')
            sleep(3)
            pg.moveTo(514,412)
            pg.click()
            pg.write('01')
            sleep(2)
            pg.moveTo(595,412)
            pg.click()
            pg.write('2022')
            sleep(2)
            pg.moveTo(514,445)
            pg.click()
            pg.write('123')
            sleep(2)
            pg.moveTo(514,489)
            pg.click()
            pg.write('12345')
            sleep(2)
            pg.moveTo(514,568)
            pg.click()
            pg.write('XYZ')
            sleep(2)
            pg.moveTo(949,637)
            pg.click()
            sleep(7)
            pg.moveTo(1005,696)
            pg.click()
            sleep(2)
            self.click_element_advanced(BillPaymentLocator.REGISTER_FORM, BillPaymentLocator.BTN_CANCEL)
            sleep(5)
            