from selenium.webdriver.common.by import By
from pages.page_base import PageBase
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.common.keys import Keys
import os, re, os.path
from time import sleep
import pyautogui as pg

class PrePostMigLocator(object):
    MIGRATION_WINDOW = (By.CLASS_NAME, 'ATL:Eon00205')
    BTN_NEXT = (By.NAME, 'Next >')
    TAB_PERSONAL_DETAILS = (By.NAME, 'Personal Details')
    TAB_OTHERS = (By.NAME, 'Other')
    PROCEED_BTN_PARENT = (By.CLASS_NAME, 'Internet Explorer_Server')
    PROCEED_BTN_CHILD = (By.NAME, 'PROCEED')
    BTN_CANCEL = (By.NAME, 'CANCEL')
    BTN_NO_MATCH = (By.NAME, 'No Match')
    CHK_ACCEPT_TERMS = (By.ID, '1002')
    BTN_SUBMIT = (By.NAME, 'Submit')
    BTN_OK = (By.NAME, 'OK')
    HANDSET_WINDOW = (By.CLASS_NAME, 'ATL:Eon00038')
    BTN_ADD = (By.NAME, 'Add')
    BTN_CHANGE_OWNER = (By.NAME, 'Change Owner')
    WINDOW_CONFIRM_IMEI = (By.CLASS_NAME, '#32770')
class PrePostMigForm(PageBase):

    def set_postal_code(self, postal_code):
        pg.write(postal_code)
        sleep(2)
        pg.press('enter')
        sleep(5)
        pg.press('enter')
        sleep(12)

    def fill_name_address_form(self):

        '''Current Address'''
        pg.moveTo(345,245)
        pg.click()
        sleep(2)
        pg.press(['down','down','enter'])
        sleep(3)
        pg.press('enter')
        sleep(3)
        pg.press(['tab','tab','tab','tab'])
        pg.write('JOHN')
        pg.press(['tab','tab'])
        pg.write('DOE')
        pg.press(['tab','tab'])
        pg.write('10101980')
        sleep(2)
        pg.press(['tab','tab','tab'])
        sleep(2)
        pg.press(['tab','tab','tab','tab','tab'])
        sleep(2)
        pg.press(['tab','tab','tab','tab','tab','tab'])
        sleep(2)
        pg.write('5')
        sleep(2)
        self.click_element_advanced(PrePostMigLocator.MIGRATION_WINDOW, PrePostMigLocator.BTN_NEXT)
        sleep(2)
        pg.press('enter')
        sleep(2)

        '''Personal Details'''
        self.click_element_advanced(PrePostMigLocator.MIGRATION_WINDOW, PrePostMigLocator.TAB_PERSONAL_DETAILS)
        sleep(3)
        pg.moveTo(333,408)
        pg.click()
        pg.press(['down', 'enter', 'enter'])
        sleep(2)

        '''Other'''
        self.click_element_advanced(PrePostMigLocator.MIGRATION_WINDOW, PrePostMigLocator.TAB_OTHERS)
        sleep(5)
        pg.moveTo(394,325)
        pg.click()
        sleep(4)
        pg.press(['tab','down'])
        sleep(4)
        pg.press(['tab','a','tab','a','tab','a','tab','a','tab','a'])
        sleep(2)
        self.click_element_advanced(PrePostMigLocator.MIGRATION_WINDOW, PrePostMigLocator.BTN_NEXT)
        sleep(5)

    def fill_business_details(self):
        pg.press(['tab','tab','tab','tab'])
        sleep(2)
        pg.write('N')
        sleep(2)
        pg.press(['tab','down'])
        sleep(2)
        self.click_element_advanced(PrePostMigLocator.MIGRATION_WINDOW, PrePostMigLocator.BTN_NEXT)
        sleep(2)
        pg.press('enter')
        sleep(7)
        if(self.driver.find_element(*PrePostMigLocator.MIGRATION_WINDOW).find_element(*PrePostMigLocator.BTN_NO_MATCH).is_displayed()):
            self.click_element_advanced(PrePostMigLocator.MIGRATION_WINDOW, PrePostMigLocator.BTN_NO_MATCH)
        sleep(5)
        pg.press('enter')
        sleep(15)

    def set_payment_method(self):
        # pg.moveTo(569,211)
        # pg.click()
        sleep(2)
        self.click_element_advanced(PrePostMigLocator.PROCEED_BTN_PARENT, PrePostMigLocator.BTN_CANCEL)
        # sleep(10)
        # pg.moveTo(847,481)
        # pg.click()
        sleep(6)
        pg.press('enter')
        sleep(8)
        self.click_element_advanced(PrePostMigLocator.PROCEED_BTN_PARENT, PrePostMigLocator.BTN_CANCEL)
        sleep(2)
        pg.press('enter')
        sleep(6)

    def set_credit_check(self):
        pg.moveTo(361,260)
        pg.click()
        pg.write('1')
        self.click_element_advanced(PrePostMigLocator.MIGRATION_WINDOW, PrePostMigLocator.CHK_ACCEPT_TERMS)
        sleep(2)
        self.click_element_advanced(PrePostMigLocator.MIGRATION_WINDOW, PrePostMigLocator.BTN_SUBMIT)
        sleep(5)
        pg.write('111111')
        pg.press('enter')
        sleep(4)
        pg.press('enter')
        sleep(12)
        self.click_element_advanced(PrePostMigLocator.MIGRATION_WINDOW, PrePostMigLocator.BTN_NEXT)
        sleep(25)

    def sales_station(self, price_plan1, price_plan2, handset):
        pg.press('enter')
        sleep(35)
        pg.moveTo(270,286)
        pg.click()
        pg.rightClick()
        sleep(3)
        pg.press(['down', 'enter'])
        sleep(2)
        pg.write(price_plan1)
        pg.press('enter')
        sleep(5)
        pg.moveTo(186,287)
        pg.click()
        sleep(15)
        self.click_element_advanced(PrePostMigLocator.MIGRATION_WINDOW, PrePostMigLocator.BTN_OK)
        sleep(10)
        pg.moveTo(257,445)
        pg.click()
        pg.rightClick()
        sleep(3)
        pg.press(['down', 'enter'])
        sleep(2)
        pg.write(price_plan2)
        pg.press('enter')
        sleep(5)
        pg.moveTo(186,443)
        pg.click()
        sleep(15)
        self.click_element_advanced(PrePostMigLocator.MIGRATION_WINDOW, PrePostMigLocator.BTN_OK)
        sleep(20)
        pg.moveTo(647,455)
        pg.click()
        sleep(2)
        pg.moveTo(612,502)
        pg.click()
        sleep(3)
        self.click_element_advanced(PrePostMigLocator.HANDSET_WINDOW, PrePostMigLocator.BTN_ADD)
        sleep(15)
        pg.moveTo(529,157)
        pg.click()
        pg.write(handset)
        sleep(2)
        pg.moveTo(553,210)
        pg.rightClick()
        sleep(3)
        self.click_element_advanced(PrePostMigLocator.MIGRATION_WINDOW, PrePostMigLocator.BTN_OK)
        sleep(5)
        pg.moveTo(405,603)
        pg.click()
        sleep(3)
        #pg.press(['tab','tab','tab','tab','enter'])

    def change_owner(self, reason):
        self.click_element_advanced(PrePostMigLocator.MIGRATION_WINDOW, PrePostMigLocator.BTN_NEXT)
        sleep(15)
        self.click_element_advanced(PrePostMigLocator.MIGRATION_WINDOW, PrePostMigLocator.BTN_NEXT)
        sleep(10)
        # pg.press('delete')
        # pg.write(imei)
        self.click_element_advanced(PrePostMigLocator.MIGRATION_WINDOW, PrePostMigLocator.BTN_CHANGE_OWNER)
        sleep(7)
        if self.driver.find_element(*PrePostMigLocator.WINDOW_CONFIRM_IMEI).find_element(*PrePostMigLocator.BTN_OK).is_displayed():
            self.click_element_advanced(PrePostMigLocator.WINDOW_CONFIRM_IMEI, PrePostMigLocator.BTN_OK)
            sleep(8)
        pg.press('tab')
        pg.write(reason)
        pg.press(['tab','tab','tab','tab','tab','tab','down'])

